- name: Create a new EC2 instance
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    image: "{{ image }}"
    instance_type: "{{ instance_type }}"
    region: "{{ region }}"
    group: "{{ group }}"
    instance_tags: "{{ instance_tags }}"
    key_name: "{{ key_name }}"
    exact_count: "{{ count }}"
    count_tag:
      "{{ instance_tags }}"
