---
- name: Gather facts of the EC2 instances on AWS
  ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
  register: ec2_remote_facts
  
- debug: msg={{ ec2_remote_facts }} 
